### PR TITLE
handle equal signs in link element's text

### PR DESCRIPTION
**Pull request by shlomif**

### CODE REVIEW

**Comment by mojavelinux** [comment]
The correct solution here is to enclose the linked text in double quotes. In other words:

```
https://example.org["foo=bar"]
```

**Comment by shlomif** [comment]
> The correct solution here is to enclose the linked text in double quotes. In other words:
> 
> ```
> https://example.org["foo=bar"]
> ```

what if it already contains them?

**Comment by mojavelinux** [comment]
Then they would have to be escaped using a backslash.

```
https://example.com["foo=\"bar\""]
```

**Comment by shlomif** [comment]
On Mon, 11 Apr 2022 01:10:06 -0700
Dan Allen ***@***.***> wrote:

> Then they would have to be escaped using a backslash.
> 
> ```
> https://example.com["foo=\"bar\""]
> ```
> 

thanks!

is there a list of characters whose presence necessitates wrapping the link's
text? I hate markup soup sometimes… 

-- 

Shlomi Fish       https://www.shlomifish.org/
https://ccmixter.org/files/destinazione_altrove/49997 - “Paint The Sky”

When Chuck Norris drops a cat, it falls on its back so it won’t lose
eye contact with Chuck.
    — https://www.shlomifish.org/humour/bits/facts/Chuck-Norris/

Please reply to list if it's a mailing list post - https://shlom.in/reply .

**Comment by mojavelinux** [comment]
The attribute list parsing is described in detail on the following page in the docs: https://docs.asciidoctor.org/asciidoc/latest/macros/link-macro-attribute-parsing/

**Comment by mojavelinux** [comment]
Thanks!

**Comment by shlomif** [comment]
@mojavelinux : thanks - and - yw

**Pull request merged**
