### PR TITLE
Various fixes and improvements

### PR DESCRIPTION
**Pull request by Hextremist**
Hi,

I got bored and decided to try to convert the Docbook V5.0 Howto found here:

http://www.docbook.org/docs/howto/

into asciidoc.  I found quite a few problems, as you can see from the number of changes.  It works pretty well now after all the changes (not quite sure which version I used).  A couple of things surprise me:

```
Co-occurrencesfootnote:[RELAX NG gram...]
```

This seems to work fine without a space in front of footnote....

```
I'm using Altova XMLSpy to validate DocBook V5.0 instances against the W3C XML S
chema ([path]_docbook.xsd_). XMLSpy complains about undefined `xml:id` attribute
s?::
```

This seem to be converted correctly by asciidoctor-pdf, but not asciidoctor output looks strange.  Do you see the same problem?

### CODE REVIEW

**Comment by mojavelinux** [comment]
Thanks! I'll review asap. Sorry for the delay.

**Comment by mrietveld** [comment]
@Hextremist Thanks! I'm actually developing on top of your branch -- the recent 2 PR's I submitted I actually developed first on top of your branch, and then cherry-picked them to master to create the PR.

**Comment by mojavelinux** [comment]
Sorry I've fallen behind on this. I'll try to get these merged soon so that you can continue building on master.

**Comment by mrietveld** [comment]
Thanks @mojavelinux ! :)

**Comment by mrietveld** [comment]
@Hextremist I've managed to merge almost all of your commits except for https://github.com/asciidoctor/docbookrx/pull/19/commits/d42ece52e3f10e16e171b3ee69f1ce7ad95ef10c

Do you have an example we could use to test that code? Thanks!

**Comment by mrietveld** [comment]
Merged (with the exception of https://github.com/asciidoctor/docbookrx/pull/19/commits/d42ece52e3f10e16e171b3ee69f1ce7ad95ef10c). 

See: 
- https://github.com/asciidoctor/docbookrx/commit/053eadd749f2945cf5007fb3924ac41139a58b9a
- https://github.com/asciidoctor/docbookrx/commit/2be5a9fe2e8e0f7ff5f87a0121c40ab289702be1
- https://github.com/asciidoctor/docbookrx/commit/1315055496ba78861324a63fa286d4a3906cb584
- https://github.com/asciidoctor/docbookrx/commit/486fdab733f7758554d1ca015b15b8f014094cd0
- https://github.com/asciidoctor/docbookrx/commit/5c437cdbe702c2735972778a9e353787c6ea6245
- https://github.com/asciidoctor/docbookrx/commit/e5b66429015178fa8de1719ae3ad8fc15b52337f
- https://github.com/asciidoctor/docbookrx/commit/f7f47f19b605745ada3fa8b73a6b0fa0982d6a2d
- https://github.com/asciidoctor/docbookrx/commit/784bfd54b5bfb6f8428ec675511cd649bd86c410

**Comment by Hextremist** [comment]
http://www.sagehill.net/docbookxsl/Db5Entities.html

I doubt that the code is complete, but as far as I remember it worked for the simple

<?xml version="1.0"?>
<!DOCTYPE book [
<!ENTITY company "Acme Widgets, Inc.">
<!ENTITY product "Top Widget">
...
]>

.
.
I love &company;!
.
.

**Pull request closed without merging**
